name: Create Pre-release

on:
  push:
    branches: [main]

env:
  BUILD_CONFIGURATION: Release
  SOURCE_DIRECTORY: ./api

jobs:
  build:
    name: Create new Pre-release
    # if: "!contains(join(github.event.commits.*.message), '+norelease')"
    if: "contains(join(github.event.commits.*.message), '+release')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.406'

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with:
          useConfigFile: true

      - name: Create Release Asset - Gateway
        run: |
          dotnet publish ${{ env.SOURCE_DIRECTORY }}/Gateway.csproj -o Gateway -c ${{ env.BUILD_CONFIGURATION }} -p:VersionPrefix="${{ steps.gitversion.outputs.majorMinorPatch }}" -p:AssemblyVersion="${{ steps.gitversion.outputs.assemblySemVer }}" -p:FileVersion="${{ steps.gitversion.outputs.assemblySemFileVer }}" -p:IncludeSymbols=true

          pushd Gateway
            zip -r ../Gateway.zip *
          popd

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Setup Assets Directory
        uses: actions/github-script@v4
        with:
          script: |

            await io.mkdirP('assets/arm')
            await io.mkdirP('assets/artifacts')
            const options = { recursive: true, force: false, copySourceDirectory: true}
            await io.cp('arm/artifacts', 'assets/artifacts', options);

      - name: Compile Bicep to ARM
        run: python ./tools/compile-arm.py

      - name: Prepare Assets
        id: prepare_assets
        run: python ./tools/create-index.py ${{ steps.gitversion.outputs.majorMinorPatch }}

      # - name: Get CLI Version
      #   id: cli_version
      #   run: python ./tools/cli-version.py
      # - name: Build CLI
      #   run: bash ./tools/build-cli.sh

      - name: Publish Release Assets
        id: publish_assets
        uses: actions/github-script@v4
        with:
          script: |

            const fs = require('fs');

            const assets = JSON.parse('${{steps.prepare_assets.outputs.assets}}');

            // const cli_name = 'lab_gateway-${{ steps.cli_version.outputs.version }}-py2.py3-none-any.whl';

            // assets.append({'name': cli_name, 'path': 'dist/' + cli_name});

            const releaseResult = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v${{ steps.gitversion.outputs.majorMinorPatch }}',
              name: 'v${{ steps.gitversion.outputs.majorMinorPatch }}-pre',
              prerelease: true,
              body: 'Pre-release build.'
            });

            const release = releaseResult.data;

            assets.forEach(async a => await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              name: a.name,
              data: fs.readFileSync(a.path)
            }));
      # - name: Upload Release Asset - CLI WHL
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: dist/lab_gateway-${{ steps.cli_version.outputs.version }}-py2.py3-none-any.whl
      #     asset_name: lab_gateway-${{ steps.cli_version.outputs.version }}-py2.py3-none-any.whl
      #     asset_content_type: application/zip
